kind: Deployment
apiVersion: apps/v1
metadata:
  name: submariner-addon
  namespace: open-cluster-management
  labels:
    app: submariner-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submariner-addon
  template:
    metadata:
      labels:
        app: submariner-addon
    spec:
      serviceAccountName: submariner-addon
      containers:
      - name: submariner-addon
        image: quay.io/open-cluster-management/submariner-addon:latest
        imagePullPolicy: IfNotPresent
        args:
          - "/submariner"
          - "controller"
        env:
        - name: BROKER_API_SERVER
          valueFrom:
            configMapKeyRef:
              name: submariner-broker-config
              key: apiserver
        - name: SUBMARINER_VERSION
          valueFrom:
            configMapKeyRef:
              name: submariner-broker-config
              key: version
