apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:submariner-addon-machinesets-aggregate-clusterrole
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["machine.openshift.io"]
    resources: ["machinesets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
