apiVersion: submariner.io/v1alpha1
kind: Submariner
metadata:
  name: submariner
  namespace: submariner-operator
spec:
  broker: k8s
  brokerK8sApiServer: {{ .BrokerAPIServer }}
  brokerK8sApiServerToken: {{ .BrokerToken }}
  brokerK8sCA: {{ .BrokerCA }}
  brokerK8sRemoteNamespace: {{ .BrokerNamespace }}
  cableDriver: {{ .CableDriver }}
  ceIPSecDebug: false
  ceIPSecIKEPort: {{ .IPSecIKEPort }}
  ceIPSecNATTPort: {{ .IPSecNATTPort }}
  ceIPSecPSK: {{ .IPSecPSK }}
  clusterCIDR: ""
  clusterID: {{ .ClusterName }}
  colorCodes: blue
  debug: false
  namespace: submariner-operator
  natEnabled: {{ .NATEnabled }}
  serviceCIDR: ""
  serviceDiscoveryEnabled: true
